name: Continuous Integration

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Check Out Code 
              uses: actions/checkout@v2
            
            - name: Setup .Net 8
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: "8.0.x"
            
            - name: Start SQL Server
              run:
                docker run -d -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=@Raj0806' -e 'MSSQL_PID=Express' -p 1433:1433 -d mcr.microsoft.com/windows/servercore:ltsc2022

            - name: Sleep for 30 seconds
              run: Start-Sleep -s 30
              shell: powershell
            
            - name: Restore Dependencies
              run: dotnet restore

            - name: Build app
              run: dotnet build -c Release --no-restore

            - name: Run automated Tests
              env: 
                ConnectionStrings__DefaultConnection: Server=localhost;Database=API_CHECK;User=sa;Password=@Raj0806
              run: dotnet test -c Release --no-restore


